on: [pull_request, deployment_status]

jobs:
  test-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: jwalton/gh-find-current-pr@v1
        id: findPrNumber

      - name: Log workflow context
        uses: actions/github-script@v5
        env:
          PR_NUMBER: ${{ steps.findPr.outputs.pr }}
        with:
          script: |
            console.log('pr number', process.env.PR_NUMBER)
